### ISSUE TITLE
Continue dropdown menu, add css

### ISSUE THREAD

**Issue by codemk8** [Foogle7/git_sandbox#7]
I just pushed a commit that rolled back some of your previous changes. After loading the csv file, it looks like this:

![image](https://user-images.githubusercontent.com/36788126/92832752-0ad3e100-f3a6-11ea-9808-0a41190d5264.png)

The reason I rolled it back is that I still want to allow the user to choose his/her file, instead of a hardcoded file. 

The new tasks are:

- [x] Add css to the dropdown menu
- [x] On the console, print what header the user chooses once the user clicks on one of the header.

**Comment by codemk8** [comment]
A cool website I just saw today:

https://knowherenews.com/covid

**Comment by andrewz4184** [comment]
I did a little formatting on the dropdown and file upload area but I don't want to add fonts or pictures or anything yet because it'll probably be annoying to transfer over github. 
![image](https://user-images.githubusercontent.com/69803093/93110237-0ef04f00-f683-11ea-82fa-f66f07125e28.png)
This will print out the option that the user clicked on in console and on the screen. 

Also I am continuing to learn Java in school (AP Programming 2 Java), and I would like to do out of school java projects possibly as it would also benefit my learning in school.

**Comment by codemk8** [comment]
good job!
